version: "3"

networks:
  laradock_backend:
    external: true

services:
  mysql-backup:
    environment:
      - MULTI_FILES=yes
      - MYSQL_HOST=mariadb
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=root
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_BUCKET=dzango-backups
      - S3_ENDPOINT=https://s3.eu-central-1.wasabisys.com
      - S3_PREFIX=mariadb
      - S3_REGION=eu-central-1
      - S3_S3V4=yes
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - SCHEDULE=@daily      
    image: dzangolab/mysql-backup-s3:latest
    networks:
      - laradock_backend
