version: "3.1"

services:
  mysql:
    image: mysql:5.7
    container_name: easyappointments-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=easyappointments
    restart: unless-stopped

  app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    container_name: easyappointments-app
    ports:
      - 8000:80
    restart: unless-stopped
    environment:
      - BASE_URL=http://localhost:8000
      - LANGUAGE=english
      - DEBUG_MODE=FALSE
      - DB_HOST=mysql
      - DB_NAME=easyappointments
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - GOOGLE_SYNC_FEATURE=FALSE
      - GOOGLE_PRODUCT_NAME=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
