FROM scratch

LABEL org.opencontainers.image.authors="info@dzangolab.com"
LABEL org.opencontainers.image.description="A custom Docker image adding support for Docker secrets"
LABEL org.opencontainers.image.documentation="https://github.com/dzangolab/dockerfiles/tree/main/docker-secrets"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/dzangolab/dockerfiles/tree/main/docker-secrets"
LABEL org.opencontainers.image.title="Dzangolab/Docker secrets"
LABEL org.opencontainers.image.url="https://dzango.com"
LABEL org.opencontainers.image.vendor="Dzango Technologies"
LABEL org.opencontainers.image.version="0.9"

COPY expand_secrets.sh /expand_secrets.sh
