FROM scratch

LABEL org.opencontainers.image.authors="info@dzangolab.com"
LABEL org.opencontainers.image.description="A customer Docker image for the Open-source time tracker [Kimai](https://www.kimai.org/) app with added support for docker secrets."
LABEL org.opencontainers.image.documentation="https://github.com/dzangolab/dockerfiles/tree/main/docker-secrets"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/dzangolab/dockerfiles/tree/main/docker-secrets"
LABEL org.opencontainers.image.title="Dzangolab/Docker secrets"
LABEL org.opencontainers.image.url="https://dzango.com"
LABEL org.opencontainers.image.vendor="Dzango Technologies"
LABEL org.opencontainers.image.version="0.5"

COPY expand_secrets.sh /expand_secrets.sh
