name: twenty

secrets:
  twentycrm-app-secret:
    file: twentycrm-app-secret
  twentycrm-database-password:
    file: twentycrm-database-password

services:
  change-vol-ownership:
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"
    image: ubuntu
    user: root
    volumes:
      - docker-data:/tmp/docker-data
      - server-local-data:/tmp/server-local-data

  db:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/twentycrm-database-password
      POSTGRES_USER: postgres
    healthcheck:
      interval: 5s
      retries: 10
      test: pg_isready -U postgres -h localhost -d postgres
      timeout: 5s
    image: postgres:16
    restart: always
    secrets:
      - twentycrm-database-password
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  server:
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      APP_SECRET_FILE: twentycrm-app-secret
      NODE_PORT: 3000
      PG_DATABASE_HOST: db
      PG_DATABASE_PASSWORD_FILE: /run/secrets/twentycrm-database-password
      PG_DATABASE_USER: twentycrm
      REDIS_URL: redis://redis:6379
      SERVER_URL: http://localhost:3000

      # AUTH_GOOGLE_APIS_CALLBACK_URL: ${AUTH_GOOGLE_APIS_CALLBACK_URL}
      # AUTH_GOOGLE_CALLBACK_URL: ${AUTH_GOOGLE_CALLBACK_URL}
      # AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      # AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # AUTH_MICROSOFT_APIS_CALLBACK_URL: ${AUTH_MICROSOFT_APIS_CALLBACK_URL}
      # AUTH_MICROSOFT_CALLBACK_URL: ${AUTH_MICROSOFT_CALLBACK_URL}
      # AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      # AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      # AUTH_MICROSOFT_ENABLED: ${AUTH_MICROSOFT_ENABLED}
      # CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      # CALENDAR_PROVIDER_MICROSOFT_ENABLED: ${CALENDAR_PROVIDER_MICROSOFT_ENABLED}
      # EMAIL_DRIVER: ${EMAIL_DRIVER:-smtp}
      # EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-contact@yourdomain.com}
      # EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-"John from YourDomain"}
      # EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-smtp.gmail.com}
      # EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
      # EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-465}
      # EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      # EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS:-system@yourdomain.com}
      # MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      # MESSAGING_PROVIDER_MICROSOFT_ENABLED: ${MESSAGING_PROVIDER_MICROSOFT_ENABLED}
      # STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      # STORAGE_S3_NAME: dzangolab-pulumi-state
      # STORAGE_S3_REGION: ap-southeast-1
      # STORAGE_TYPE: local

    healthcheck:
      interval: 5s
      retries: 10
      test: curl --fail http://localhost:3000/health
      timeout: 5s
    image: twentycrm/twenty:v0.44
    ports:
      - "3000:3000"
    restart: always
    secrets:
      - twentycrm-app-secret
      - twentycrm-database-password
    volumes:
      - docker-data:/app/docker-data
      - server-local-data:/app/packages/twenty-server/.local-storage

  worker:
    command: ["yarn", "worker:prod"]
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    environment:
      APP_SECRET_FILE: /run/secrets/twentycrm-app-secret
      DISABLE_DB_MIGRATIONS: "true" # it already runs on the server
      PG_DATABASE_HOST: db
      PG_DATABASE_PASSWORD_FILE: /run/secrets/twentycrm-database-password
      PG_DATABASE_USER: twentycrm
      REDIS_URL: redis://redis:6379
      SERVER_URL: http://localhost:3000

      # AUTH_GOOGLE_APIS_CALLBACK_URL: ${AUTH_GOOGLE_APIS_CALLBACK_URL}
      # AUTH_GOOGLE_CALLBACK_URL: ${AUTH_GOOGLE_CALLBACK_URL}
      # AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      # AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # AUTH_MICROSOFT_APIS_CALLBACK_URL: ${AUTH_MICROSOFT_APIS_CALLBACK_URL}
      # AUTH_MICROSOFT_CALLBACK_URL: ${AUTH_MICROSOFT_CALLBACK_URL}
      # AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      # AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      # AUTH_MICROSOFT_ENABLED: ${AUTH_MICROSOFT_ENABLED}
      # CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      # CALENDAR_PROVIDER_MICROSOFT_ENABLED: ${CALENDAR_PROVIDER_MICROSOFT_ENABLED}
      # EMAIL_DRIVER: ${EMAIL_DRIVER:-smtp}
      # EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-contact@yourdomain.com}
      # EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-"John from YourDomain"}
      # EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-smtp.gmail.com}
      # EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
      # EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-465}
      # EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      # EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS:-system@yourdomain.com}
      # MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      # MESSAGING_PROVIDER_MICROSOFT_ENABLED: ${MESSAGING_PROVIDER_MICROSOFT_ENABLED}
      # STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      # STORAGE_S3_NAME: dzangolab-pulumi-state
      # STORAGE_S3_REGION: ap-southeast-1.
      # STORAGE_TYPE: local

    image: twentycrm/twenty:v0.44
    restart: always
    secrets:
      - twentycrm-app-secret
      - twentycrm-database-password

volumes:
  db-data:
  docker-data:
  server-local-data: